### ISSUE TITLE
Feature request: Download models automatically from model zoo

### ISSUE THREAD

**Issue by reuben** [coqui-ai/STT#1859]

**Comment by philipp2310** [comment]
I probably will implement something like that in python for Project Alice as running without manual setup is one of the main goals for me (as soon as Coqui runs on raspberry again, as this is currently my only test setup) - I was able to program C quite some time ago in university, so I could get back to that as well - with some guidance maybe, because I never had the connection of python and C ;)
The "only" thing I care is a simple "out of the box" experience, if Coqui can use the "on the fly" language installation or if it is in Alice isn't a big factor for me, but a central implementation might help more people (hey there rhasspy and co ;)) and should be preferable! Therefore my offer to get back into C and get it running here!

Is there some more of a concept by you how the models should be shared? (german general ML is currently on google drive, your english/mandarin is on the github release etc.)

Best Regards and thanks again for your awesome software!

**Comment by reuben** [comment]
@philipp2310 We're currently working on automatic installations integrated with the [Coqui Model Zoo](https://coqui.ai/models). All models there are released under a consistent format with proper attribution and metadata, and we think that's how models should be shared and installed. For now we're not integrating it directly into libstt.so, to ease prototyping and figuring out the details, but that could change in the future. We should have something to share pretty soon :)

**Comment by philipp2310** [comment]
Sounds good!
Was it an active decision to not include the generic .scorer language model?
While it is the biggest file, on raspberries an on device trained .scorer isn't feasible I think.
And a custom pre-trained one isn't helpful in my usecase, as the user decides what skills he wants to install and therefor what text can be captured -> I would land at a generic one anyways!
(An idea I just had, but didn't have the time to look into it yet: Is it possible to have small .scorer files for lets say 5 types of sentences and combine them to a bigger file with some reduced computation time? I'll investigate later and learn a bit about your scorer structures :) )

**Comment by reuben** [comment]
We should have scorers available on the model zoo soon. That's a pre-requisite for releasing the automatic installation :)

**Comment by reuben** [comment]
>  (An idea I just had, but didn't have the time to look into it yet: Is it possible to have small .scorer files for lets say 5 types of sentences and combine them to a bigger file with some reduced computation time? I'll investigate later and learn a bit about your scorer structures :) )

Not really, you should simply combine the 5 corpora and create a single scorer.

**Comment by reuben** [comment]
This has been implemented in STT model manager for a while now.
