### ISSUE TITLE
Feature request: parallelize generate_lm.py

### ISSUE THREAD

**Issue by JRMeyer** [coqui-ai/STT#1881]
If you have a feature request, then please provide the following information:

**Is your feature request related to a problem? Please describe.**
Training a 5-gram language model on 13G of text takes a *very long time* (hours?) and only uses one CPU.

**Describe the solution you'd like**
I'd like to use all my CPUs in parallel to finish the job faster.

**Describe alternatives you've considered**
Training the LM on a lower resource machine is about the only option I can think of, to not waste time on bigger machines.

**Additional context**
None.

**Comment by reuben** [comment]
As far as I know KenLM is fundamentally optimized for streaming processing of datasets bigger than RAM, in the order of hundreds of gigabytes, rather than compute parallelism. You would need to reimplement LM estimation from scratch, and that's if Kneser-Ney smoothing even allows for this from an algorithmic perspective (in which case you'd need to replace KenLM with something fundamentally different like a Transformer).

**Comment by reuben** [comment]
Since solving this issue requires a change that is much larger in scope, I'm closing this issue.
