### ISSUE TITLE
Bug: Illegal instruction (core dumped) ,

### ISSUE THREAD

**Issue by Siyamfahad** [coqui-ai/STT#2225]
I am trying to install stt for training my own model but I am facing this issue called Illegal instruction (core dumped),

I tried using docker and manually both ways but got the same result, I also tried with TensorFlow GPU and CPU version same result :(
can anyone help me with this?

terminal log

**(coqui-stt-train-venv) siyamfahad@siyamfahad-VirtualBox:~/STT$ ./bin/run-ldc93s1.sh

[ ! -f train.py ]
[ ! -f data/smoke_test/ldc93s1.csv ]
checkpoint_dir=/home/siyamfahad/.local/share/stt/ldc93s1
export CUDA_VISIBLE_DEVICES=0
python -m coqui_stt_training.train --alphabet_config_path data/alphabet.txt --show_progressbar false --train_files data/smoke_test/ldc93s1.csv --test_files data/smoke_test/ldc93s1.csv --train_batch_size 1 --test_batch_size 1 --n_hidden 100 --epochs 200 --checkpoint_dir /home/siyamfahad/.local/share/stt/ldc93s1
Illegal instruction (core dumped)
(coqui-stt-train-venv) siyamfahad@siyamfahad-VirtualBox:/STT$ python -m coqui_stt_training.train --help
Illegal instruction (core dumped)
(coqui-stt-train-venv) siyamfahad@siyamfahad-VirtualBox:/STT$**
My CPU is i7-4770
my GPU is gtx-1050ti

**Comment by Siyamfahad** [comment]
I found the issue was for my GPU, after removing it its working well, i don't know why my gpu makes this issue ,please reopen the issue if anyone can help

**Comment by fquirin** [comment]
Can we reopen this please.

Some of my [SEPIA STT-Server](https://github.com/SEPIA-Framework/sepia-stt-server/) users experience the [same issue](https://github.com/SEPIA-Framework/sepia-docs/issues/218) when running Coqui on a VM or as Docker container in a Synology DS920+ (CPU Intel Celeron J4125).

For the Proxmox VM the solution was `"setting the hypervisor CPU type to host instead of default"`.
I think this [Stackoverflow issue](https://stackoverflow.com/questions/70256751/tensorflow-on-docker-engine-error-code-132) might be related as well ("Intel Celeron J4125 [...] does not support AVX and AVX2 instructions").

It seems that some dependency of Coqui STT has requirements for a certain CPU instructions set. Although I don't understand how this would relate to the OP's GPU issue 🤔
